### ISSUE TITLE
Drupal 10 compatibility

### ISSUE THREAD

**Issue by kayakr** [asulibraries/islandora_matomo#8]
As reported via `drupal/upgrade_status`:
- [x] `web/modules/contrib/islandora_matomo/src/IslandoraMatomoService.php` Call to deprecated function file_create_url(). Deprecated in drupal:9.3.0 and is removed from drupal:10.0.0. Use the appropriate method on \Drupal\Core\File\FileUrlGeneratorInterface instead.
- [x] `web/modules/contrib/islandora_matomo/modules/islandora_matomo_blocks/src/Plugin/Block/IslandoraNodeAllMediaDownloadsBlock.php` Missing explicit access check on entity query.
- [x] `web/modules/contrib/islandora_matomo/modules/islandora_matomo_blocks/src/Plugin/Block/IslandoraNodeViewsAndOriginalFileSummedDownloadsBlock.php` Missing explicit access check on entity query.
- [x] `web/modules/contrib/islandora_matomo/islandora_matomo.info.yml` Value of core_version_requirement: ^8 || ^9 is not compatible with the next major version of Drupal core. See https://drupal.org/node/3070687.
- [x] `web/modules/contrib/islandora_matomo/modules/islandora_matomo_blocks/islandora_matomo_blocks.info.yml` Value of core_version_requirement: ^8 || ^9 is not compatible with the next major version of Drupal core. See https://drupal.org/node/3070687.

**Comment by kayakr** [comment]
See [PR!](https://github.com/asulibraries/islandora_matomo/pull/9/files)

**Comment by seth-shaw-asu** [comment]
Sorry I missed this somehow! I ended up doing this in a separate PR: https://github.com/asulibraries/islandora_matomo/commit/03ee6a48d0266e3838f29280c22435b7d5f18778
